name: Run Tests for GH-LeakSealer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        mongo_uri: ${{ secrets.MONGO_URI }}
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
      run: |
        python -m unittest discover -s tests -p "test_*.py"